# Generated by Django 5.2.1 on 2025-07-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Imagem de Destaque')),
                ('post_type', models.CharField(choices=[('ARTIGO', 'Artigo Científico'), ('DICA', 'Dica de Cultivo')], default='DICA', max_length=10, verbose_name='Tipo de Post')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PENDING', 'Pendente de Revisão'), ('PUBLISHED', 'Publicado')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='É destaque?')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Resumo do Artigo')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='articles_pdf/', verbose_name='Arquivo PDF')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(help_text='Usado para URLs amigáveis.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Post',
                'verbose_name_plural': 'Categorias de Posts',
                'ordering': ['name'],
            },
        ),
    ]
